### ISSUE TITLE
Firmwareaktualisierung nicht möglich

### ISSUE THREAD

**Issue by olav83** [enigmagroup/enigmasuite#3]
Hallo Enigma Freunde,

es besteht mal wieder ein Problem mit meiner Enigmabox.
Da die alte Enigmasuite-Software ja nicht mehr weiterentwickelt wird, hatte ich mir dieses Wochenende vorgenommen das Firmwareupdate über den Menüpunkt "Firmwareaktualisierung" auf der Weboberfläche durchzuführen.

Habe alle Anweisungen korrekt befolgt, den USB-Stick eingesteckt, formatiert, das Backup draufziehn lassen und danach den Stick wieder entfernt.

Darauf wurde das Firmwareupdate heruntergeladen, soweit so gut..

Bloß nun habe ich folgendes Problem:

![screencapture-box-upgrade](https://cloud.githubusercontent.com/assets/6561108/6432549/c4758ce2-c055-11e4-99ed-2e322875d378.jpg)

Beim folgenden Schritt, wobei die Firmware aufgespielt wird, sollte man um die 10 Minuten warten. Nach ca. 15 Minuten versuchte ich auf die Weboberfläche zuzugreifen, ohne Erfolg.

Nach etwa 2 Stunden steckte ich die Box aus, da sie immer noch nicht erreichbar war.
Zu meinem Verwundern startete die alte Firmware nach dem wieder einstecken, als ob gar keine Aktualisierung vorgenommen wurde.

Auch nach einem weiteren Versuch, konnte ich das Update nicht installieren.

Woran könnte das liegen?

**Comment by enigmagroup** [comment]
Alle Zeichen deuten darauf hin, dass das Paket "busybox-static" nicht installiert wurde - warum auch immer.

1) Via SSH einloggen
2) apt-get install busybox-static

Dann nochmal probieren.

**Comment by olav83** [comment]
busybox-static ist eigentlich schon installiert.

Habe folgende Ausgabe bekommen:

![ausgabe](https://cloud.githubusercontent.com/assets/6561108/6433000/8dcba15e-c064-11e4-9c12-ec9cc8d32c27.jpg)

**Comment by enigmagroup** [comment]
Hmm, ok.

Wirf den Upgrader mal manuell an - mich nimmt die Ausgabe wunder:

```upgrader download_image```
```upgrader run```

Den Stick mit dem Backup hast du ja bereits, gell?

**Comment by olav83** [comment]
Der Stick mit dem Backup wurde erstellt, richtig.

Das Upgrade hat leider wieder nicht funktioniert, obwohl ich weit über die vorgeschriebenen 10 Minuten gewartet habe.

Die Ausgabe der Befehle war folgende:

![upgrader run](https://cloud.githubusercontent.com/assets/6561108/6444039/46a504a4-c0fb-11e4-8388-a88b1968431b.jpg)

Mit "upgrader run" bin ich aus der Konsole geflogen, da ja der SSH Service beendet wird.

**Comment by enigmagroup** [comment]
Mist.

Wir haben noch andere Boxen, wo auch kein Upgrade läuft. Bei dem meisten tut es, nur bei wenigen nicht, das macht es gerade so schwierig nachzustellen. Zum Glück tritt es bei einem Bekannten auf, bei dem ich via Teamviewer draufschauen kann. Kann das allerdings erst in ein paar Tagen erledigen.

**Comment by olav83** [comment]
Schon was neues zum Upgrade-Problem herausgefunden?

Ich bin mittlerweile überzeugt, dass außer dem Beenden der Dienste, nichts weitereres vom Upgrade-Script durchgeführt wird..

**Comment by enigmagroup** [comment]
Hab die Person noch nicht erreicht für die Teamviewersitzung, aber sie müsste sich bis heute Abend melden. Stay tuned.

**Comment by enigmagroup** [comment]
Alles klar, wir haben das Problem eingekreist.

1. Den USB-Stick an der Enigmabox einstecken und nicht am PC :P
2. Pakete konnten nicht authentiziert werden. Ist behoben und wird diese Nacht ausgerollt.

Morgen müsste es klappen.

**Comment by olav83** [comment]
Haha, aber nichts für ungut, mein Stick war schon in der Engimabox ;)

Freut mich, dass der Fehler gefunden wurde, dann werd ich das Update morgen nochmals probieren.

**Comment by olav83** [comment]
Selbes Phänomen, wie mit der alten Version.
Nach dem Warten der 10 Minuten läuft nichts mehr..

Die Weboberfläche zeigt folgendes zur Version an: Enigmasuite Version -4 (9. März 1615)

**Comment by enigmagroup** [comment]
Gopferdamminunndediä. Wa.rum. Seufz.

Vielleicht sollten wir mal Teamviewer machen. Ich weiss sonst langsam echt nicht mehr weiter.

**Comment by olav83** [comment]
Teamviewer wär machbar.

Wann sollen wir die Sitzung veranstalten?
Heute Abend so um 20:00 Uhr wär z.B. meinerseits in Ordnung.

**Comment by enigmagroup** [comment]
Mir geht es diese Woche leider erst ab Donnerstag.

Wäre Donnerstag, 20:00 ok?

**Comment by olav83** [comment]
Ja, der Termin ist mir auch recht.

**Comment by enigmagroup** [comment]
42@enigmabox.net, um alles weitere zu besprechen.

**Comment by olav83** [comment]
Gute Idee, habe die Verbindungsdaten an die Mail-Adresse gesendet.

**Comment by olav83** [comment]
Mail bekommen? Ich bin bereit und warte ..

**Comment by enigmagroup** [comment]
Jup sorry, bin grad fertiggeworden mit dem Nachtessen.

**Comment by olav83** [comment]
Folgendes hat die Konsole noch kurz nach dem Upgrade-Befehl ausgeben:

![box-upgrade](https://cloud.githubusercontent.com/assets/6561108/6626981/1a2b209a-c8fb-11e4-8f90-59498fbd9c9d.jpg)

Die linke LED der Engimabox hat angefangen zu blicken.
Jetzt warte ich mal..

**Comment by enigmagroup** [comment]
Das ist gut.

"busybox top" gibt sonst die Prozessanzeige aus. da müssten Dinge wie "zcat" und "dd" zu sehen sein...

**Comment by olav83** [comment]
Ok, dann wart ich jetzt noch um die 7 Minuten..

**Comment by olav83** [comment]
So, lange genug gewartet.
Nichts ist passiert, Weboberfläche und SSH nicht erreichbar.
Jetzt bin ich über den COM-Port auf die Box, das Debian läuft schön weiter, bloß SSH usw. sind beendet worden. Die linke LED blinkt immer noch..

**Comment by olav83** [comment]
Ich tendiere dazu, dass ich jetzt einfach Plan B einschlage.

Den Backup-Stick kann ich unter Windows nicht lesen. Ist auf dem Stick eine Kopie mit allem Wichtigem von der Enigmabox gemacht worden?

**Comment by enigmagroup** [comment]
Die linke LED blinkt: Gut! D.h. das Update ist immer noch im Gange. Wobei *eigentlich* müsste jetzt die mittlere LED blinken...

**Comment by enigmagroup** [comment]
Oh, Plan B - joa. Ja, der Stick ist *nur* für die Enigmabox formatiert worden - hoffentlich hat Windows jetzt nichts darauf zerstört... :S

**Comment by enigmagroup** [comment]
Den Stick brauchst du dann nach dem Plan B für den Restore. Ist im Webinterface Schritt für Schritt beschrieben, dann.

**Comment by enigmagroup** [comment]
Also dann viel Erfolg!

**Comment by olav83** [comment]
Ich denke die linke LED hat beim Anfang auch geblinkt. Bloß ich habe ganze 2 Stunden gewartet nichts passierte.

Stick wird schon passen. Den Zugangsschlüssel sollte ich noch auf anderen Engima-Stick haben. Ich versuche jetzt Plan B.

**Comment by enigmagroup** [comment]
Prima!

**Comment by olav83** [comment]
Ok, sieht gut aus, die Oberfläche kommt, der Stick wurde angenommen.
Bloß eine Sache fällt mir jetzt noch auf, warum wird trotzdem noch der Punkt "Firmwareupdate" angezeigt? Muss ich nochmals updaten?

**Comment by enigmagroup** [comment]
Hurra!

> warum wird trotzdem noch der Punkt "Firmwareupdate" angezeigt? Muss ich nochmals updaten?

Firmwareupdate ist jetzt fix mit dabei - für die Zukunft und falls du die Box mal wieder komplett zurücksetzen möchtest (ok, in diesem Fall bei OpenWrt werden die Konfigurationen im Ram gesichert und wiederhergestellt - ausser den E-Mails, da zu wenig Ram/Platz).
